In [21]:
import numpy as np
import pandas as pd

In [2]:
a1 = np.array([1,2,3])

In [9]:
a1.shape

(3,)

In [10]:
a2 = np.array([[1,2,3]])

In [11]:
a2.shape

(1, 3)

In [13]:
a1.ndim, a2.ndim

(1, 2)

In [14]:
a1.size

3

In [16]:
a2.size

3

In [18]:
a2 = np.array([[1,2,3],
               [4,5,6]
              ])

In [19]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
pd.DataFrame(a2)

0  1  2
0  1  2  3
1  4  5  6

In [26]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.ones((2,3)).shape

(2, 3)

In [31]:
np.arange(1,10, 2)

array([1, 3, 5, 7, 9])

In [34]:
np.random.randint(4, 7, size=(3, 5))

array([[6, 4, 4, 4, 5],
       [5, 6, 6, 5, 6],
       [6, 4, 6, 4, 6]])

In [36]:
np.random.random((2, 3))

array([[0.16997647, 0.96159312, 0.50198849],
       [0.4366427 , 0.61401744, 0.39480913]])

In [42]:
np.random.rand(2, 3)

array([[0.60999994, 0.04806463, 0.37451532],
       [0.79898528, 0.42618503, 0.24064848]])

In [38]:
np.random.seed()